---
format_version: 3
environments:
  internal:
    pipelines:
      - gocd-trial-installer
pipelines:
  gocd-trial-installer:
    group: go-cd-contrib
    materials:
      github:
        git: https://git.gocd.io/git/gocd-contrib/gocd-trial-launcher
        destination: launcher
      installers:
        pipeline: installers
        stage: dist
      codesigning:
        git: https://github.com/gocd/codesigning
        destination: codesigning
      signing-keys:
        svn: https://github.com/gocd-private/signing-keys/trunk
        username: gocd-ci-user
        encrypted_password: "AES:taOvOCaXsoVwzIi+xIGLdA==:GSfhZ6KKt6MXKp/wdYYoyBQKKzbTiyDa+35kDgkEIOF75s9lzerGInbqbUM7nUKc"
        destination: signing-keys
    environment_variables:
      GOCD_JRE_URL: https://s3.amazonaws.com/mirrors-archive/local/jdk
      GOCD_JRE_VERSION: 11.0.2
    stages:
      - build:
          elastic_profile_id: ecs-golang-build
          artifacts:
            - build:
                source: dist/**/*
                destination: dist/
          tasks:
          - exec:
              command: /bin/bash
              arguments:
                - build.sh
                - --verbose
                - --prod
                - --release=Edge
              working_directory: launcher
          - exec:
              command: mv
              arguments:
                - dist
                - ..
              working_directory: launcher
      - code-signing:
          secure_variables:
            GOCD_GPG_PASSPHRASE: "AES:7lAutKoRKMuSnh3Sbg9DeQ==:8fhND9w/8AWw6dJhmWpTcCdKSsEcOzriQNiKFZD6XtN+sJvZ65NH/QFXRNiy192+SSTKsbhOrFmw+kAKt5+MH1Erd6H54zJjpSgvJUmsJaQ="
          jobs:
            osx:
              artifacts:
                - build:
                    source: osx.zip
              resources:
                - mac
                - signer
              tasks:
              - fetch:
                  stage: build
                  job: build
                  source: dist/
              - exec:
                  command: /bin/bash
                  arguments:
                    - launcher/codesigning-helpers/osx-codesign.sh
                    - dist/darwin/amd64/run-gocd
              - exec:
                  command: zip
                  arguments:
                    - osx.zip
                    - dist/darwin/amd64/run-gocd
            win:
              elastic_profile_id: window-dev-build
              artifacts:
                - build:
                    source: win.zip
              tasks:
              - fetch:
                  stage: build
                  job: build
                  source: dist/
              - exec:
                  command: call
                  arguments:
                    - launcher\codesigning-helpers\win-codesign.bat
      - package:
          elastic_profile_id: ecs-golang-build
          artifacts:
            - build:
                source: installers/*
                destination: installers/
          tasks:
          - fetch:
              pipeline: installers
              stage: dist
              job: dist
              source: dist/zip/
              destination: deps/
          - fetch:
              stage: build
              job: build
              source: dist/
          - exec:
              command: mv
              arguments:
                - dist
                - deps
                - launcher/
          - exec:
              command: /bin/bash
              arguments:
                - package.sh
                - osx
                - linux
                - windows
              working_directory: launcher
          - exec:
              command: mv
              arguments:
                - launcher/installers
                - .
