---
format_version: 3
pipelines:
  gocd-trial-installer:
    group: go-cd-contrib
    materials:
      github:
        git: https://git.gocd.io/git/gocd-contrib/gocd-trial-launcher
      installers:
        pipeline: installers
        stage: dist

    stages:
      - build:
          elastic_profile_id: ecs-golang-build
          artifacts:
            - build:
                source: dist/**/*
          tasks:
          - exec:
              command: /bin/bash
              arguments:
                - build.sh
                - --verbose
                - --prod
                - --release=Edge
      - package:
          tasks:
          - fetch:
              pipeline: installers
              stage: dist
              job: dist
              source: dist/zip/
              destination: deps/
          - fetch:
              stage: build
              job: build
              source: dist/
              destination: dist/
          - exec:
              command: ls
              arguments:
                - -lR
