---
format_version: 3
pipelines:
  gocd-trial-installer:
    group: go-cd-contrib
    materials:
      github:
        git: https://git.gocd.io/git/gocd-contrib/gocd-trial-launcher
      installers:
        pipeline: installers
        stage: dist
    environment_variables:
      GOCD_JRE_URL: https://s3.amazonaws.com/mirrors-archive/local/jdk
      GOCD_JRE_VERSION: 11.0.2
    stages:
      - build:
          elastic_profile_id: ecs-golang-build
          artifacts:
            - build:
                source: dist/**/*
                destination: dist/
          tasks:
          - exec:
              command: /bin/bash
              arguments:
                - build.sh
                - --verbose
                - --prod
                - --release=Edge
      - package:
          elastic_profile_id: ecs-golang-build
          artifacts:
            - build:
                source: installers/*.zip
                destination: installers/
          tasks:
          - fetch:
              pipeline: installers
              stage: dist
              job: dist
              source: dist/zip/
              destination: deps/
          - fetch:
              stage: build
              job: build
              source: dist/
              destination: dist/
          - exec:
              command: /bin/bash
              arguments:
                - package.sh
